# src/memory/gold_filter.py
"""
Gold filter – отбирает успешные эпизоды из памяти для будущего обучения.
Gold filter – selects successful episodes from memory for future training.
"""
from __future__ import annotations

import hashlib
from dataclasses import dataclass
from typing import Any, Iterable


@dataclass
class ExperienceSample:
    """
    Represents a single experience sample collected from a node's interactions,
    along with its associated success score and metadata.

    Attributes:
        instruction (str): The instruction or task given to the agent.
        input_text (str): The context or input provided to the agent.
        output_text (str): The successful action or response generated by the agent.
        score (float): A quantitative measure of the success or quality of this experience,
                       clamped between 0.0 and 1.0.
        meta (dict[str, Any]): Additional metadata about the sample (e.g., event ID, node ID).
    """
    instruction: str
    input_text: str
    output_text: str
    score: float
    meta: dict[str, Any]


def _normalize_text(text: str) -> str:
    """
    Normalizes a given text string by converting it to lowercase,
    removing leading/trailing whitespace, and collapsing multiple
    internal spaces into single spaces.

    Args:
        text (str): The input string to normalize.

    Returns:
        str: The normalized string.
    """
    return " ".join(text.lower().strip().split())


def calculate_success_score(entry: dict[str, Any]) -> float:
    """
    Простая версия скоринга.
    Позже можно заменить более точной формулой.
    Calculates a success score for an experience entry based on various metrics.
    This is a simple version of the scoring function; it can be replaced with a
    more sophisticated formula in the future.

    The score is calculated as a weighted sum of PnL delta, efficiency, peer validation,
    and a risk penalty. The final score is clamped between 0.0 and 1.0.

    Args:
        entry (dict[str, Any]): A dictionary containing various metrics for an experience.
                                Expected keys include "pnl_delta", "efficiency",
                                "peer_validation", and "risk_penalty".

    Returns:
        float: The calculated success score, ranging from 0.0 to 1.0.
    """
    pnl = float(entry.get("pnl_delta", 0.0))
    efficiency = float(entry.get("efficiency", 0.0))
    peer = float(entry.get("peer_validation", 0.0))
    risk_penalty = float(entry.get("risk_penalty", 0.0))

    score = (
        0.50 * pnl +
        0.25 * efficiency +
        0.25 * peer -
        0.40 * risk_penalty
    )

    return max(0.0, min(1.0, score))


def deduplicate_samples(samples: Iterable[ExperienceSample]) -> list[ExperienceSample]:
    """
    Deduplicates a list of ExperienceSample objects based on their normalized
    instruction, input_text, and output_text.

    A SHA256 hash is used to create a fingerprint for each sample, ensuring
    that only unique experiences (in terms of content) are retained.

    Args:
        samples (Iterable[ExperienceSample]): An iterable of experience samples to deduplicate.

    Returns:
        list[ExperienceSample]: A new list containing only the unique experience samples.
    """
    seen: set[str] = set()
    result: list[ExperienceSample] = []

    for sample in samples:
        # Create a unique fingerprint based on the normalized core text components
        fingerprint = hashlib.sha256(
            f"{_normalize_text(sample.instruction)}\n"
            f"{_normalize_text(sample.input_text)}\n"
            f"{_normalize_text(sample.output_text)}".encode("utf-8")
        ).hexdigest()

        if fingerprint in seen:
            continue
        seen.add(fingerprint)
        result.append(sample)

    return result


def filter_gold_samples(
    entries: Iterable[dict[str, Any]],
    threshold: float = 0.8,
) -> list[ExperienceSample]:
    """
    Filters a collection of raw experience entries to select "gold" samples
    that meet a specified success score threshold.

    Each entry is scored using `calculate_success_score`, and only those
    exceeding the `threshold` are converted into `ExperienceSample` objects.
    Finally, the collected samples are deduplicated.

    Args:
        entries (Iterable[dict[str, Any]]): An iterable of raw experience dictionaries.
        threshold (float): The minimum success score required for an entry to be
                           considered a "gold" sample. Defaults to 0.8.

    Returns:
        list[ExperienceSample]: A deduplicated list of `ExperienceSample` objects
                                that passed the scoring threshold.
    """
    samples: list[ExperienceSample] = []

    for entry in entries:
        score = calculate_success_score(entry)
        if score < threshold:
            continue

        samples.append(
            ExperienceSample(
                instruction=str(entry.get("task_description", "")),
                input_text=str(entry.get("market_context", "")),
                output_text=str(entry.get("successful_action", "")),
                score=score,
                meta={
                    "event_id": entry.get("event_id"),
                    "node_id": entry.get("node_id"),
                    "source": entry.get("source", "memory"),
                    "adapter_id": entry.get("adapter_id"),
                },
            )
        )

    return deduplicate_samples(samples)
