# src/memory/gold_filter.py
"""
Gold filter – отбирает успешные эпизоды из памяти для будущего обучения.
Gold filter – selects successful episodes from memory for future training.
"""
from __future__ import annotations

import hashlib
from dataclasses import dataclass
from typing import Any, Dict, Iterable, List, Set


@dataclass
class ExperienceSample:
    """
    Represents a single experience sample collected from a node's interactions,
    along with its associated success score and metadata.

    Attributes:
        instruction: The instruction or task given to the agent.
        input_text: The context or input provided to the agent.
        output_text: The successful action or response generated by the agent.
        score: A quantitative measure of the success or quality of this experience,
               clamped between 0.0 and 1.0.
        meta: Additional metadata about the sample (e.g., event ID, node ID).
    """
    instruction: str
    input_text: str
    output_text: str
    score: float
    meta: Dict[str, Any]


def _normalize_text(text: str) -> str:
    """
    Normalizes a given text string by converting it to lowercase,
    removing leading/trailing whitespace, and collapsing multiple
    internal spaces into single spaces.

    Args:
        text: The input string to normalize.

    Returns:
        The normalized string.
    """
    return " ".join(text.lower().strip().split())


def calculate_success_score(entry: Dict[str, Any]) -> float:
    """
    Calculates a success score for an experience entry based on various metrics.
    This is a simple version of the scoring function; it can be replaced with a
    more sophisticated formula in the future.

    The score is calculated as a weighted sum of PnL delta, efficiency, peer validation,
    and a risk penalty. The final score is clamped between 0.0 and 1.0.

    Args:
        entry: A dictionary containing various metrics for an experience.
               Expected keys include "pnl_delta", "efficiency", "peer_validation",
               and "risk_penalty". Missing keys will default to 0.0.

    Returns:
        The calculated success score, ranging from 0.0 to 1.0.
    """
    pnl: float = float(entry.get("pnl_delta", 0.0))
    efficiency: float = float(entry.get("efficiency", 0.0))
    peer: float = float(entry.get("peer_validation", 0.0))
    risk_penalty: float = float(entry.get("risk_penalty", 0.0))

    score: float = (
        0.50 * pnl +
        0.25 * efficiency +
        0.25 * peer -
        0.40 * risk_penalty
    )

    return max(0.0, min(1.0, score))


def deduplicate_samples(samples: Iterable[ExperienceSample]) -> List[ExperienceSample]:
    """
    Deduplicates a list of ExperienceSample objects based on their normalized
    instruction, input_text, and output_text content.

    A SHA256 hash is used to create a fingerprint for each sample, ensuring
    that only unique experiences (in terms of content) are retained.

    Args:
        samples: An iterable of experience samples to deduplicate.

    Returns:
        A new list containing only the unique experience samples.
    """
    seen_fingerprints: Set[str] = set()
    unique_samples: List[ExperienceSample] = []

    for sample in samples:
        # Create a unique fingerprint based on the normalized core text components.
        # Ensure consistent encoding for hashing.
        fingerprint: str = hashlib.sha256(
            f"{_normalize_text(sample.instruction)}\n"
            f"{_normalize_text(sample.input_text)}\n"
            f"{_normalize_text(sample.output_text)}".encode("utf-8")
        ).hexdigest()

        if fingerprint in seen_fingerprints:
            continue  # Skip if this content fingerprint has already been seen
        
        seen_fingerprints.add(fingerprint)
        unique_samples.append(sample)

    return unique_samples


def filter_gold_samples(
    entries: Iterable[Dict[str, Any]],
    threshold: float = 0.8,
) -> List[ExperienceSample]:
    """
    Filters a collection of raw experience entries to select "gold" samples
    that meet a specified success score threshold.

    Each entry is scored using `calculate_success_score`. Only those entries
    exceeding the `threshold` are converted into `ExperienceSample` objects.
    Finally, the collected samples are deduplicated to ensure content uniqueness.

    Args:
        entries: An iterable of raw experience dictionaries.
        threshold: The minimum success score required for an entry to be
                   considered a "gold" sample. Defaults to 0.8.

    Returns:
        A deduplicated list of `ExperienceSample` objects that passed
        the scoring threshold.
    """
    gold_samples: List[ExperienceSample] = []

    for entry in entries:
        score: float = calculate_success_score(entry)
        if score < threshold:
            continue  # Skip entries that do not meet the minimum score

        # Extract values safely, defaulting to empty strings for text fields.
        # The meta dictionary fields can genuinely be None, so `entry.get` is appropriate.
        instruction: str = str(entry.get("task_description", ""))
        input_text: str = str(entry.get("market_context", ""))
        output_text: str = str(entry.get("successful_action", ""))

        meta_data: Dict[str, Any] = {
            "event_id": entry.get("event_id"),
            "node_id": entry.get("node_id"),
            "source": entry.get("source", "memory"),
            "adapter_id": entry.get("adapter_id"),
        }

        gold_samples.append(
            ExperienceSample(
                instruction=instruction,
                input_text=input_text,
                output_text=output_text,
                score=score,
                meta=meta_data,
            )
        )

    return deduplicate_samples(gold_samples)
