from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Literal


PatchType = Literal[
    "replace_function",
    "replace_class",
    "replace_import",
    "replace_block",
    "replace_file",
    "insert_before",
    "insert_after",
    "delete",
]


@dataclass
class FileItem:
    path: str
    content: str
    size_kb: float
    language: str = "python"
    imports: List[str] = field(default_factory=list)
    fingerprint: str = ""


@dataclass
class MemoryHit:
    kind: str
    score: float
    payload: Dict[str, Any]


@dataclass
class ValidationResult:
    syntactically_valid: bool = False
    compile_ok: bool = False
    ruff_ok: Optional[bool] = None
    mypy_ok: Optional[bool] = None
    pytest_ok: Optional[bool] = None
    patch_applied_ok: Optional[bool] = None
    notes: List[str] = field(default_factory=list)


@dataclass
class PatchOperation:
    """
    One local edit instruction generated by the LLM.

    The agent can later apply these operations deterministically using AST/libCST
    or a safe text-based fallback.
    """
    type: PatchType
    target: str
    new_code: str = ""
    summary: str = ""
    reason: str = ""
    confidence: float = 0.0
    scope: str = ""
    before: str = ""
    after: str = ""


@dataclass
class FilePatchPlan:
    """
    One file-level plan returned by the model.
    """
    path: str
    action: Literal["patch", "replace_file", "skip"] = "patch"
    summary: str = ""
    risk: float = 0.0
    tags: List[str] = field(default_factory=list)
    patches: List[PatchOperation] = field(default_factory=list)
    full_code: str = ""
    notes: str = ""


@dataclass
class DraftResponse:
    """
    Top-level structured response from the planner model.
    """
    files: List[FilePatchPlan] = field(default_factory=list)
    overall_summary: str = ""
    overall_risk: float = 0.0
    should_repair: bool = False
    critique_notes: str = ""


@dataclass
class CritiqueResponse:
    """
    Structured critique from the critic model.
    """
    approved: bool = False
    overall_risk: float = 0.0
    blocking_issues: List[str] = field(default_factory=list)
    non_blocking_suggestions: List[str] = field(default_factory=list)
    preferred_action: str = ""
    critique: str = ""


@dataclass
class ProposalItem:
    path: str
    description: str
    reason: str
    code_skeleton: str = ""
    risk: float = 0.0
    tags: List[str] = field(default_factory=list)


@dataclass
class ProposalResponse:
    proposals: List[ProposalItem] = field(default_factory=list)
    summary: str = ""


@dataclass
class ImprovementResult:
    original_path: str
    proposed_path: str
    code: str
    language: str = "python"
    risk: float = 0.0
    summary: str = ""
    changed_lines_ratio: float = 1.0
    score: float = 0.0
    validation: ValidationResult = field(default_factory=ValidationResult)
    memory_tags: List[str] = field(default_factory=list)
    critique: str = ""
    strategy: str = "default"
    patches: List[PatchOperation] = field(default_factory=list)
    fallback_used: bool = False