services:
  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  market:
    build:
      context: ../..
    image: blackswan-market:latest
    entrypoint: ["python", "-m", "mvp.lab_swarm_demo.market_service"]
    environment:
      - REDIS_URL=redis://redis:6379
      - DRIFT=0.002
      - VOLATILITY=0.01
      - PYTHONUNBUFFERED=1          # <-- добавьте эту строку
    depends_on:
      redis:
        condition: service_healthy

  node:
    build:
      context: ../..            # корень проекта
    image: blackswan-node:latest
    entrypoint: ["/app/mvp/lab_swarm_demo/node_entrypoint.sh"]
    environment:
      - REDIS_URL=redis://redis:6379
      - BURN_RATE=0.1
      - FAILURE_PROB=0.0
    deploy:
      replicas: 8
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    depends_on:
      redis:
        condition: service_healthy
      market:
        condition: service_started